name: "Docker: Build and Publish"

on:
  release:
    types: [published]

jobs:
  build_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract tag name
        id: vars
        run: |
          # GITHUB_REF_NAME is e.g. 'v1.0.0'
          echo "TAG_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build . \
            --file Dockerfile.prod \
            --tag ${{ secrets.DOCKER_HUB_USERNAME }}/edtlab:latest \
            --tag ${{ secrets.DOCKER_HUB_USERNAME }}/edtlab:${{ env.TAG_NAME }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/edtlab:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/edtlab:${{ env.TAG_NAME }}
